# Generated by Django 6.0 on 2026-07-02 19:14

from django.db import migrations, models


def populate_slugs(apps, schema_editor):
    Campaign = apps.get_model('blood_request', 'Campaign')
    from django.utils.text import slugify
    for obj in Campaign.objects.all():
        if not obj.slug:
            slug = slugify(obj.title)
            orig_slug = slug
            counter = 1
            while Campaign.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
                slug = f"{orig_slug}-{counter}"
                counter += 1
            obj.slug = slug
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0046_announcement_expiry_date_announcement_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, help_text='Campaign end date', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, help_text='Campaign start date', null=True),
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
    ]
