# Generated by Django 6.0 on 2026-07-09 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0049_alter_policyreport_options_policyreport_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='beneficiary_text',
            field=models.TextField(blank=True, help_text='Who will benefit from this campaign?', null=True),
        ),
        migrations.CreateModel(
            name='CampaignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='campaigns/documents/')),
                ('file_size', models.CharField(blank=True, help_text='e.g. 1.2 MB (will auto-calculate if blank)', max_length=50, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blood_request.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaigns/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blood_request.campaign')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
