# Generated by Django 6.0 on 2026-07-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0051_internshiprequest_cv_internshiprequest_dob_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshiprequest',
            options={'verbose_name': 'Internship Certificate', 'verbose_name_plural': 'Internship Certificates'},
        ),
    ]
