# Generated by Django 6.0 on 2026-07-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0052_alter_internshiprequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshiprequest',
            options={'verbose_name': 'Internship Request', 'verbose_name_plural': 'Internship Requests'},
        ),
    ]
