# Generated by Django 6.0 on 2026-07-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0054_alter_internshiprequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20)),
                ('education', models.CharField(choices=[('High School', 'High School'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Other', 'Other')], max_length=50)),
                ('employment', models.CharField(choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed'), ('Housewife', 'Housewife'), ('Student', 'Student'), ('Retired', 'Retired'), ('Other', 'Other')], max_length=50)),
                ('cv', models.FileField(upload_to='volunteer_cvs/')),
                ('residence', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Volunteer Request',
                'verbose_name_plural': 'Volunteer Requests',
            },
        ),
    ]
