# Generated by Django 6.0 on 2026-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0055_volunteerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusambassadorapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='campusambassadorapplication',
            name='college',
        ),
        migrations.RemoveField(
            model_name='campusambassadorapplication',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='campusambassadorapplication',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='ambassador_cvs/'),
        ),
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='general_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='motivation',
            field=models.TextField(blank=True, help_text='Why do you want to join as a Campus Ambassador?', null=True),
        ),
        migrations.AddField(
            model_name='campusambassadorapplication',
            name='technical_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
