# Generated by Django 6.0 on 2026-07-26 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_request", "0056_remove_campusambassadorapplication_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="admin_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="category",
            field=models.CharField(
                choices=[
                    ("Medical", "Medical"),
                    ("Education", "Education"),
                    ("Animal Welfare", "Animal Welfare"),
                    ("Disaster Relief", "Disaster Relief"),
                    ("NGO", "NGO"),
                    ("Child Care", "Child Care"),
                    ("Emergency", "Emergency"),
                    ("Memorial", "Memorial"),
                    ("Startup", "Startup"),
                    ("Personal Need", "Personal Need"),
                    ("Sports", "Sports"),
                    ("Community", "Community"),
                    ("Environment", "Environment"),
                    ("Other", "Other"),
                ],
                default="Medical",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="confirmation_agreed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="campaigns/covers/"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="currency",
            field=models.CharField(
                choices=[
                    ("INR", "₹ INR"),
                    ("USD", "$ USD"),
                    ("EUR", "€ EUR"),
                    ("GBP", "£ GBP"),
                ],
                default="INR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="short_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending Review", "Pending Review"),
                    ("Under Verification", "Under Verification"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Need Documents", "Need Documents"),
                    ("Suspended", "Suspended"),
                ],
                default="Approved",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaigndocument",
            name="file_size",
            field=models.CharField(
                blank=True, help_text="e.g. 1.2 MB", max_length=50, null=True
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beneficiary_name", models.CharField(max_length=200)),
                ("bank_name", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=50)),
                ("ifsc_code", models.CharField(max_length=20)),
                ("upi_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cancelled_cheque",
                    models.FileField(
                        blank=True, null=True, upload_to="campaigns/bank/"
                    ),
                ),
                ("ifsc_verified", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to="blood_request.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("Myself", "Myself"),
                            ("Someone Else", "Someone Else"),
                            ("Organization", "Organization"),
                        ],
                        default="Myself",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("id_type", models.CharField(blank=True, max_length=50, null=True)),
                ("id_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "id_proof_file",
                    models.FileField(
                        blank=True, null=True, upload_to="campaigns/beneficiaries/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiary",
                        to="blood_request.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("step_data", models.JSONField(default=dict)),
                ("current_step", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heard_from", models.CharField(blank=True, max_length=100, null=True)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_info",
                        to="blood_request.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="campaigns/updates/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="blood_request.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aadhaar_file",
                    models.FileField(blank=True, null=True, upload_to="campaigns/kyc/"),
                ),
                (
                    "pan_file",
                    models.FileField(blank=True, null=True, upload_to="campaigns/kyc/"),
                ),
                (
                    "passport_file",
                    models.FileField(blank=True, null=True, upload_to="campaigns/kyc/"),
                ),
                (
                    "selfie_file",
                    models.FileField(blank=True, null=True, upload_to="campaigns/kyc/"),
                ),
                (
                    "face_match_score",
                    models.IntegerField(
                        default=95, help_text="Biometric face match percentage"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending Verification"),
                            ("Verified", "Verified"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("email_verified", models.BooleanField(default=True)),
                ("phone_verified", models.BooleanField(default=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="blood_request.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_name", models.CharField(max_length=200)),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("diagnosis", models.TextField()),
                (
                    "treatment_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("treatment_start_date", models.DateField(blank=True, null=True)),
                (
                    "medical_report",
                    models.FileField(
                        blank=True, null=True, upload_to="campaigns/medical/"
                    ),
                ),
                (
                    "prescription_file",
                    models.FileField(
                        blank=True, null=True, upload_to="campaigns/medical/"
                    ),
                ),
                (
                    "cost_estimate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="campaigns/medical/"
                    ),
                ),
                (
                    "hospital_letter",
                    models.FileField(
                        blank=True, null=True, upload_to="campaigns/medical/"
                    ),
                ),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_detail",
                        to="blood_request.campaign",
                    ),
                ),
            ],
        ),
    ]
