# Generated by Django 5.2.7 on 2026-09-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0058_alter_blog_image_blogimage'),
        ('blood_request', '0059_blog_category'),
    ]

    operations = [
    ]
