# Generated by Django 6.0 on 2026-01-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0003_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Staff notes or completion comments"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Review", "Review"),
                    ("Done", "Done"),
                ],
                default="To Do",
                max_length=20,
            ),
        ),
    ]
