# Generated by Django 6.0 on 2026-01-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0004_task_priority_task_remarks_alter_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
