# Generated by Django 6.0 on 2026-01-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0007_interaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="content",
            field=models.TextField(
                blank=True, help_text="Full HTML content for the detail page"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=255, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(help_text="Short excerpt for the card"),
        ),
    ]
