# Generated by Django 6.0 on 2026-01-30 11:34

from django.db import migrations
from datetime import date

def populate_projects(apps, schema_editor):
    Project = apps.get_model('blood_request', 'Project')
    
    projects_data = [
        {
            "title": "Enabling Future Through Youth Empowerment",
            "slug": "enabling-future-through-youth-empowerment",
            "date": date(2025, 5, 26),
            "description": "UDAAN Society Joins Hands with Bandhan Skill Development Centre for Youth Empowerment...",
            "image": "projects/image 1.jpeg",
            "content": """<p class="section-text">
                <span class="emoji">☀️</span> UDAAN Society Joins Hands with Bandhan Skill Development Centre for Youth
                Empowerment <span class="emoji">☀️</span>
            </p>

            <p>
                We are thrilled to announce a transformative collaboration between <strong>UDAAN Society</strong> and
                <strong>Bandhan Skill Development Centre</strong>, marking a significant step toward youth empowerment
                and holistic community development in the <strong>Aligarh region</strong>.
            </p>

            <div class="project-vision">
                <h3><span class="emoji">👁️</span> The Vision</h3>
                <p>
                    For over 13 years, Bandhan Skill Development Centre has been a beacon of hope for thousands of
                    underprivileged youths across India. With <strong>57,023 youths trained</strong> and <strong>43,046
                        successfully placed</strong> across various sectors in states like West Bengal, Odisha, Bihar,
                    and Uttar Pradesh, their impact is both deep and far-reaching.
                </p>
                <p>
                    <span class="emoji">💼</span> These youths are now earning respectable livelihoods with average
                    monthly incomes ranging from <strong>₹12,000 to ₹24,000</strong>, along with access to additional
                    perks and growth opportunities—proving that skill training truly changes lives.
                </p>
            </div>

            <div class="project-partnership">
                <h3><span class="emoji">🤝</span> The Partnership</h3>
                <p>
                    This collaboration between <strong>Bandhan</strong> and <strong>UDAAN Society</strong> is built on a
                    shared mission—to foster 360-degree development by combining our unique strengths:
                </p>
                <ul>
                    <li><strong>UDAAN Society</strong> will spearhead <strong>youth mobilization</strong> in the Aligarh
                        region, engaging, counseling, and enrolling motivated young individuals.</li>
                    <li><strong>Bandhan Skill Development Centre</strong> will deliver <strong>industry-relevant
                            training</strong> and facilitate <strong>job placements</strong>, ensuring that youth are
                        skilled, certified, and connected to sustainable career opportunities.</li>
                </ul>
            </div>

            <div class="project-why-it-matters">
                <h3><span class="emoji">💡</span> Why It Matters</h3>
                <p>
                    At a time when unemployment and skill gaps remain major challenges, this partnership stands as a
                    model of how grassroots organizations and institutional skill providers can come together to create
                    real, measurable impact. Together, we are not just building careers—we are building confidence,
                    self-reliance, and hope.
                </p>
                <p>
                    <span class="emoji">📢</span> Stay tuned for training schedules, mobilization drives, and success
                    stories from the field. Let's rise together to uplift youth and empower communities!
                </p>
            </div>

            <div class="program-poster">
                <img src="https://udaansociety.org/media/project_images/WhatsApp_Image_2024-01-29_at_20.25.10_1.jpeg"
                    alt="Employability Skills Program Poster">
            </div>

            <div class="registration-info">
                <h3>KEY HIGHLIGHTS:-</h3>
                <div class="highlights-content">
                    <ul>
                        <li><i class="fas fa-star-of-life"></i> PERSONALITY DEVELOPMENT</li>
                        <li><i class="fas fa-star-of-life"></i> COMMUNICATION SKILLS</li>
                        <li><i class="fas fa-star-of-life"></i> PROBLEM SOLVING</li>
                        <li><i class="fas fa-star-of-life"></i> INTERVIEW SKILLS</li>
                        <li><i class="fas fa-star-of-life"></i> COMPUTER SKILLS</li>
                        <li><i class="fas fa-star-of-life"></i> JOB PLACEMENT ASSISTANCE</li>
                    </ul>
                    <div class="qr-code-section">
                        <p class="scan-text">Scan For Registration</p>
                        <img src="https://udaansociety.org/media/project_images/WhatsApp_Image_2024-01-29_at_20.25.10.jpeg"
                            alt="QR Code for Registration">
                    </div>
                </div>
                <div class="contact-details">
                    <p>Association With</p>
                    <p class="bold">BANDHAN SKILL DEVELOPMENT CENTER</p>
                    <p><i class="fas fa-phone-alt"></i> +91 9639888844, 7017757843</p>
                    <p><i class="fas fa-map-marker-alt"></i> 3<sup>rd</sup> Floor ICICI Building in front of Gandhi Park
                        Aligarh</p>
                    <p><i class="fas fa-envelope"></i> BSDC.ALIGARH@BANDHAN.ORG</p>
                </div>
            </div>"""
        },
        {
            "title": "Shiksha Plus Initiative With Shiv Nadar Foundation",
            "slug": "shiksha-plus-initiative-with-shiv-nadar-foundation-impacting-3000-lives-with-education",
            "date": date(2024, 12, 4),
            "description": "The Shiksha Plus initiative is a program by the Shiv Nadar Foundation...",
            "image": "projects/image 2.jpeg",
            "content": "<p>Content coming soon...</p>"
        },
        {
            "title": "Operation And Management Of Shelter Homes Project",
            "slug": "operation-and-management-of-shelter-homes-project",
            "date": date(2024, 2, 16),
            "description": "The shelter homes are constructed under the central government's Shelter for Urban...",
            "image": "projects/image 3.jpeg",
            "content": "<p>Content coming soon...</p>"
        },
        {
            "title": "Atal Bhujal Yojna",
            "slug": "atal-bhujal-yojna",
            "date": date(2024, 2, 16),
            "description": "UDAAN society is working as a District Implementation Partner(DIP) under this project...",
            "image": "projects/image 4.png",
            "content": "<p>Content coming soon...</p>"
        },
        {
            "title": "Partnership With AALI",
            "slug": "partnership-with-aali",
            "date": date(2024, 2, 16),
            "description": "(A project on gender disparities and discrimination issues and gender-based violence risk)...",
            "image": "projects/image 5.jpeg",
            "content": "<p>Content coming soon...</p>"
        },
        {
            "title": "PM Svanidhi Project",
            "slug": "pm-svanidhi-project",
            "date": date(2024, 2, 16),
            "description": "UDAAN Society is Working as an Implementation Agency for Aligarh Nagar Nigam...",
            "image": "projects/image 6.png",
            "content": "<p>Content coming soon...</p>"
        },
        {
            "title": "Jal Jeevan Mission-Har Ghar Jal Project",
            "slug": "jal-jeevan-mission-har-ghar-jal-project",
            "date": date(2024, 2, 16),
            "description": "UDAAN Society is appointed an Implementation support Agency under Jal Jeevan Mission...",
            "image": "projects/image 7.png",
            "content": "<p>Content coming soon...</p>"
        },
        {
            "title": "Child Line-1098",
            "slug": "child-line-1098",
            "date": date(2024, 2, 15),
            "description": "CHILDLINE 1098 is a phone number that spells hope for millions of...",
            "image": "projects/image 8.png",
            "content": "<p>Content coming soon...</p>"
        }
    ]

    for data in projects_data:
        Project.objects.get_or_create(
            slug=data['slug'],
            defaults=data
        )

class Migration(migrations.Migration):
    dependencies = [
        (
            "blood_request",
            "0008_project_content_project_slug_task_completion_lat_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_projects),
    ]
