# Generated by Django 5.2.10 on 2026-02-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0011_sync_reports'),
        ('blood_request', '0013_remove_blog_slug_remove_blog_subtitle_and_more'),
    ]

    operations = [
    ]
