# Generated by Django 5.2.10 on 2026-02-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0014_merge_20260204_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='No content'),
            preserve_default=False,
        ),
    ]
