# Generated by Django 6.0 on 2026-02-05 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0015_blog_content"),
        ("blood_request", "0016_remove_duplicate_blogs"),
    ]

    operations = []
