# Generated by Django 6.0 on 2026-02-05 04:54

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0017_merge_0015_blog_content_0016_remove_duplicate_blogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="content",
            field=models.TextField(
                blank=True, help_text="Full HTML content for the detail page"
            ),
        ),
    ]
