# Generated by Django 6.0 on 2026-02-11 05:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0020_personalnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="project",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, help_text="Full HTML content for the detail page"
            ),
        ),
    ]
