# Generated by Django 6.0 on 2026-02-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0021_alter_blog_content_alter_project_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blooddonor",
            name="last_donation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
