# Generated by Django 6.0 on 2026-02-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0022_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='detailed_text',
            field=models.TextField(blank=True, help_text='Full story/details (shown on expand)', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(help_text='The testimonial quote (summary)'),
        ),
    ]
