# Generated by Django 6.0 on 2026-02-12 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0022_blooddonor_last_donation_date"),
        ("blood_request", "0023_testimonial_detailed_text_alter_testimonial_text"),
    ]

    operations = []
