# Generated by Django 6.0 on 2026-02-13 05:54

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0024_merge_20260212_1415"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("Received", "Received"),
                    ("Verified", "Verified"),
                    ("Fulfilling", "Fulfilling"),
                    ("Closed", "Closed"),
                ],
                default="Received",
                max_length=50,
                protected=True,
            ),
        ),
    ]
