# Generated by Django 6.0 on 2026-02-13 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0025_bloodrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blooddonor",
            name="donation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blooddonor",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("units", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="blood_request.blooddonor",
                    ),
                ),
            ],
        ),
    ]
