# Generated by Django 6.0 on 2026-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0028_workspace_team_workspace_workspacemember_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsClipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="news_clippings/")),
                ("newspaper", models.CharField(max_length=100)),
                (
                    "date_display",
                    models.CharField(help_text="e.g. June 2024", max_length=50),
                ),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
