# Generated by Django 6.0 on 2026-02-21 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0029_campusambassador"),
        ("blood_request", "0029_newsclipping"),
    ]

    operations = []
