# Generated by Django 6.0 on 2026-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0030_merge_0029_campusambassador_0029_newsclipping"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusAmbassadorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("college", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("year_of_study", models.CharField(max_length=50)),
                (
                    "interests",
                    models.TextField(
                        help_text="Why do you want to join as a Campus Ambassador?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Reviewed", "Reviewed"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="newsclipping",
            name="date_display",
            field=models.CharField(help_text="e.g. June 2026", max_length=50),
        ),
    ]
