# Generated by Django 6.0 on 2026-03-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0032_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="last_recurred_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_rule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Every 2 Weeks"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
