# Generated by Django 5.2.10 on 2026-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0032_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ethical', 'Ethical'), ('finance', 'Finance'), ('hr', 'HR'), ('travel', 'Travel'), ('posh', 'POSH')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='policy_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
