# Generated by Django 6.0 on 2026-03-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0033_task_last_recurred_at_task_recurrence_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharednote",
            name="parent_note",
            field=models.ForeignKey(
                blank=True,
                help_text="Nest under another note to create a Wiki",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_notes",
                to="blood_request.sharednote",
            ),
        ),
    ]
