# Generated by Django 6.0 on 2026-03-07 03:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0033_policyreport"),
        ("blood_request", "0034_sharednote_parent_note"),
    ]

    operations = []
