# Generated by Django 6.0 on 2026-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0038_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short summary of the activity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('date', models.DateField(help_text='Date of the activity')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date'],
            },
        ),
    ]
