# Generated by Django 6.0 on 2026-03-09 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0039_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this rule", max_length=200
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("task_created", "When a Task is Created"),
                            ("status_changed_done", "When Task Status Changes to Done"),
                            (
                                "status_changed_in_progress",
                                "When Task Status Changes to In Progress",
                            ),
                            (
                                "priority_set_critical",
                                "When Priority is Set to Critical",
                            ),
                            ("task_overdue", "When a Task Becomes Overdue"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_email_assignee", "Send Email to Assignee"),
                            ("send_email_manager", "Send Email to Manager/Creator"),
                            ("create_notification", "Create Portal Notification"),
                            ("auto_assign_user", "Auto-Assign to a Specific User"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target user for auto-assign or notification actions",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Automation Rule",
                "verbose_name_plural": "Task Automation Rules",
            },
        ),
    ]
