# Generated by Django 6.0 on 2026-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0040_taskautomationrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("fellowship", "Fellowship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "salary",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ₹25,000 - ₹35,000/month or 'As per experience'",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Brief intro / about the project"),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="Key responsibilities (one per line)"
                    ),
                ),
                (
                    "desired_profile",
                    models.TextField(
                        blank=True, help_text="Desired qualifications (one per line)"
                    ),
                ),
                ("project_duration", models.CharField(blank=True, max_length=300)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                (
                    "contact_email",
                    models.EmailField(default="mail@udaansociety.org", max_length=254),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="jobs/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "ordering": ["-created_at"],
            },
        ),
    ]
