# Generated by Django 6.0 on 2026-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blood_request", "0041_jobposting"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks that must be completed before this task can progress",
                related_name="dependent_tasks",
                to="blood_request.task",
            ),
        ),
    ]
