# Generated by Django 6.0 on 2026-03-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0042_task_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='available_to_donate',
            field=models.BooleanField(default=True, help_text='Currently available to donate'),
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Receive notifications via email'),
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='Hospital where blood is needed', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Emergency blood request'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_name',
            field=models.CharField(blank=True, help_text='Name of the patient', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalblooddonor',
            name='available_to_donate',
            field=models.BooleanField(default=True, help_text='Currently available to donate'),
        ),
        migrations.AddField(
            model_name='historicalblooddonor',
            name='email_notifications',
            field=models.BooleanField(default=False, help_text='Receive notifications via email'),
        ),
        migrations.AddField(
            model_name='historicalblooddonor',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalbloodrequest',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='Hospital where blood is needed', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalbloodrequest',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Emergency blood request'),
        ),
        migrations.AddField(
            model_name='historicalbloodrequest',
            name='patient_name',
            field=models.CharField(blank=True, help_text='Name of the patient', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbloodrequest',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units',
            field=models.IntegerField(default=1, help_text='Number of units/bags'),
        ),
        migrations.AlterField(
            model_name='historicalbloodrequest',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbloodrequest',
            name='units',
            field=models.IntegerField(default=1, help_text='Number of units/bags'),
        ),
    ]
