# Generated by Django 6.0 on 2026-03-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0043_newslettersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='din',
            field=models.CharField(blank=True, help_text='Donor Identification Number', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='din',
            field=models.CharField(blank=True, help_text='Request Identification Number', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalblooddonor',
            name='din',
            field=models.CharField(blank=True, db_index=True, help_text='Donor Identification Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbloodrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalbloodrequest',
            name='din',
            field=models.CharField(blank=True, db_index=True, help_text='Request Identification Number', max_length=20, null=True),
        ),
    ]
