# Generated by Django 6.0 on 2026-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0045_alter_blooddonor_blood_group_alter_blooddonor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher numbers show first'),
        ),
    ]
