# Generated by Django 6.0 on 2026-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0047_campaign_end_date_campaign_slug_campaign_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('educational_qualification', models.CharField(max_length=300)),
                ('permanent_address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('internship_area', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('duration_months', models.IntegerField(default=3)),
                ('mentor_name', models.CharField(blank=True, help_text='Required for offer letter generation', max_length=200, null=True)),
                ('mentor_email', models.EmailField(blank=True, help_text='Required for offer letter generation', max_length=254, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Internship Request',
                'verbose_name_plural': 'Internship Requests',
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Annual Report', 'verbose_name_plural': 'Annual Reports'},
        ),
    ]
