# Generated by Django 6.0 on 2026-07-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0048_internshiprequest_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyreport',
            options={'verbose_name': 'Policy Document', 'verbose_name_plural': 'Policy Documents'},
        ),
        migrations.AddField(
            model_name='policyreport',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='policyreport',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='policyreport',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policyreport',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='policy_thumbnails/'),
        ),
        migrations.AddField(
            model_name='policyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='policyreport',
            name='category',
            field=models.CharField(choices=[('ethical', 'Ethical'), ('finance', 'Finance'), ('hr', 'HR'), ('travel', 'Travel'), ('posh', 'POSH')], default='ethical', max_length=20),
        ),
    ]
