# Generated by Django 6.0 on 2026-07-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0050_campaign_beneficiary_text_campaigndocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiprequest',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='intern_cvs/'),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20),
        ),
        migrations.AddField(
            model_name='internshiprequest',
            name='other_interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
